name: Deploy Webserver

on:
  workflow_dispatch:

env:
  GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Installing essential module and library
      run: |
        python3 -m pip install requests
        sudo apt-get install jq -y
        curl -sSf https://sshx.io/get | sh
        
    - name: Deleting previous workflow
      run: |
        python3 del_workflow.py
        
    - name: Running SSHX
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        
      run: |
        python3 sshx.py
        
    - name: Instance keep-alive
      run: |
        SLEEP=$((RANDOM % 1800 + 18000))  # 18000–19799
        echo "Sleeping for $SLEEP seconds (~$((SLEEP / 60)) minutes)"
        sleep 60

        
    - name: Retrigger Workflow
      env:
        REPO: ${{ github.repository }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      run: |
        curl -X DELETE $WEBHOOK_URL/messages/$(cat /home/runner/.webhook_id)
        
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GIT_API_TOKEN" \
          https://api.github.com/repos/$REPO/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
